### ISSUE TITLE
Create Gradle Task that automatically creates releases.

### ISSUE THREAD

**Issue by jopiortiz** [ao-libre/ao-java#100]

**Comment by RecoX** [comment]
Una cosa a tener en cuenta aca es que se estan mezclando los conceptos.

Gradle no puede crear un release en github, eso se hace o manualmente o con tareas automatizadas, lease usar un script que use la API de github, genere un tag/release y adjunte el ASSET

lo que puede llegar a crear Gradle es lo que nosotros llamamos ASSETS que es lo que adjuntamos en cada release.

**Comment by guidota** [comment]
https://github.com/BreadMoirai/github-release-gradle-plugin todo se puede @RecoX

**Comment by RecoX** [comment]
bueno, ahi tenemos el script que lo hace por nosotros XD

```
This plugin uses OkHttp to send a POST requests to the github api that creates a release and uploads specified assets.
```

**Comment by guidota** [comment]
Steps:
- Build desktop module
- Packer (gradle plugin): Add jdk to bundle. For each OS.
- Zip
- Update Release

**Comment by jopiortiz** [comment]
Este es mejor (creo yo) https://github.com/trnl/github-release-gradle-plugin

**Comment by guidota** [comment]
Done
