### ISSUE TITLE
Lovely project. I will test it on raspberry pi 4.

### ISSUE THREAD

**Issue by Askmewho** [ao-libre/ao-java#126]
Keep on it. Leave this open so I could reply when I get my rpi4

**Comment by Derillo** [comment]
it worked? @Askmewho

**Comment by Askmewho** [comment]
I didnt tested yet. The rpi4 its not on argentina already. Ive give it a quick shoot on rpi3 but we need to add some arm definitions because the solution download some x86 java jars and not the arm or arm64 ones. But I cant find where is that right now. Doesnt matter, I will check it later.

**Comment by Derillo** [comment]
Thank you for your comments. We wish to have you again with news.

**Comment by Askmewho** [comment]
Indeed, I will do so. Just be patient please. Keep on it!! And thanks!
