### ISSUE TITLE
[Question] Client entities on connect

### ISSUE THREAD

**Issue by sdg9** [ao-libre/ao-java#54]
@guidota Great example of libgdx, artemis, and kryonet! 

I've been going through the code a couple days now as there are many patterns and approaches here I'm learning a great deal from.  I understand how messages are processed between client/server using the visitor pattern (thanks I'm now using that too). I see how entities are modified and removed with EntityUpdate and RemoveEntity notifications but I'm having trouble finding where the client gets their initial set of entities in the world on connection to the server. 
 Can you point me in the right direction?  
Thanks

**Comment by guidota** [comment]
hi @sdg9! every entity is registered by `WorldManager` and `MapManager`. in `MapManager` there is a map called `nearEntities` which will be updated when things happen (like new entities, movement, etc). It keep relation between entities, and we use `WorldManager::notifyToNearEntities` when we want to update and notify changes to near entities. I don't know if it is the best approach, but it works for the time being. lmk if i'm clear.

**Comment by sdg9** [comment]
@guidota thanks I'll take a look around that logic.

**Comment by Derillo** [comment]
@sdg9 we need you here! I hope you come back
